export const SET_MOBILE = 'SET_MOBILE'

export const SET_NAV = 'SET_NAV'
export const SET_NAVCLASS = 'SET_NAVCLASS'
export const SET_HTAG = 'SET_HTAG'
export const SET_INDEX = 'SET_INDEX'
export const SET_ABOUT = 'SET_ABOUT'
export const SET_PORT = 'SET_PORT'
export const SET_HOME = 'SET_HOME'
export const SET_SCROLL = 'SET_SCROLL'
export const SET_MOVE = 'SET_MOVE'
export const SET_LOAD = 'SET_LOAD'
export const SET_LINKCLASS = 'SET_LINKCLASS'
export const SET_BARS = 'SET_BARS'
