export const SET_MOBILE = 'SET_MOBILE'
export const SET_STEP = 'SET_STEP'

export const SET_NAV = 'SET_NAV'
export const SET_NAVCLASS = 'SET_NAVCLASS'
export const SET_ZINDEX = 'SET_ZINDEX'

export const SET_HTAG = 'SET_HTAG'
export const SET_SCROLL = 'SET_SCROLL'
export const SET_MOVE = 'SET_MOVE'
export const SET_OPAC = 'SET_SCREEN_OPAC'

export const SET_INDEX = 'SET_INDEX'
export const SET_ABOUT = 'SET_ABOUT'
export const SET_PORT = 'SET_PORT'
export const SET_HOME = 'SET_HOME'
export const SET_BARS = 'SET_BARS'
export const SET_LOAD = 'SET_LOAD'
export const SET_LINKCLASS = 'SET_LINKCLASS'
export const SET_DIST = 'SET_DIST'
export const LAST_SCROLL = 'LAST_SCROLL'
export const NEXT_SCROLL = 'NEXT_SCROLL'

export const SET_OUTR = 'SET_OUTR'
export const SET_OUTL = 'SET_OUTL'
export const SET_INR = 'SET_INR'
export const SET_INL = 'SET_INL'
export const SET_COUNT = 'SET_COUNT'
export const SET_PIC = 'SET_PIC'
export const SET_DATA = 'SET_DATA'
export const SET_INNER = 'SET_INNER'

export const SET_PEN_DATA = 'SET_PEN_DATA'

export const SET_POS = 'SET_POS'
export const SET_SMOOTH = 'SET_SMOOTH'

//xport const SET_OPTION = 'SET_OPTION'
export const SET_OPTION_CLASS = 'SET_OPTION_CLASS'
export const SET_PDF = 'SET_PDF'
